#!/bin/bash

PROGNAME=$(basename $0)

CONFFILE=`realpath ./config.yaml`
FORCE=0

usage()
{
cat << EOF
$PROGNAME -- create a kubernetes cluster using KVM/QEMU and RKE2|K3s in minutes
Usage:
$PROGNAME start [name] [--config <path>]  start deployment or the specified node
$PROGNAME stop [--config <path>]          stop deployment
$PROGNAME start-basevm [--config <path>]  start base virtual machine
$PROGNAME stop-basevm [--config <path>]   stop base virtual machine
$PROGNAME halt [name] [--config <path>]   halt deployment or the specified node
$PROGNAME help                            display help
EOF
}

function do_start () {
	echo "Start using $CONFFILE"

	pushd ./vagrant
	KUBE_VIRTDEPLOY_CONFIG="$CONFFILE" VAGRANT_VAGRANTFILE=Vagrantfile.server vagrant up
	KUBE_VIRTDEPLOY_CONFIG="$CONFFILE" VAGRANT_VAGRANTFILE=Vagrantfile.worker vagrant up
	popd
}

function do_stop () {
	echo "Stop using $CONFFILE"

	pushd ./vagrant
	env KUBE_VIRTDEPLOY_CONFIG="$CONFFILE" VAGRANT_VAGRANTFILE=Vagrantfile.server vagrant destroy
	env KUBE_VIRTDEPLOY_CONFIG="$CONFFILE" VAGRANT_VAGRANTFILE=Vagrantfile.worker vagrant destroy
	popd
}

function do_start_basevm () {
	echo "Start base virtual machine using $CONFFILE"

	pushd ./vagrant
	KUBE_VIRTDEPLOY_CONFIG="$CONFFILE" VAGRANT_VAGRANTFILE=Vagrantfile.base vagrant up
	popd
}

function do_stop_basevm () {
	echo "Stop base virtual machine using $CONFFILE"

	pushd ./vagrant
	env KUBE_VIRTDEPLOY_CONFIG="$CONFFILE" VAGRANT_VAGRANTFILE=Vagrantfile.base vagrant destroy
	popd
}

function do_halt () {
	echo "Halt using $CONFFILE"

	pushd ./vagrant
	if [ "x$FORCE" == x"0" ]; then
		env KUBE_VIRTDEPLOY_CONFIG="$CONFFILE" VAGRANT_VAGRANTFILE=Vagrantfile.server vagrant halt
		env KUBE_VIRTDEPLOY_CONFIG="$CONFFILE" VAGRANT_VAGRANTFILE=Vagrantfile.worker vagrant halt
	else
		env KUBE_VIRTDEPLOY_CONFIG="$CONFFILE" VAGRANT_VAGRANTFILE=Vagrantfile.server vagrant halt --force
		env KUBE_VIRTDEPLOY_CONFIG="$CONFFILE" VAGRANT_VAGRANTFILE=Vagrantfile.worker vagrant halt --force
	fi
	popd
}

function do_start_one () {
	NODE="$1"

	echo "Start up \`$NODE\`"

	if [[ "$NODE" =~ "master" ]]; then
		echo "master"
		VAGRANTFILE=Vagrantfile.server
	else
		VAGRANTFILE=Vagrantfile.worker
	fi

	pushd ./vagrant
	env KUBE_VIRTDEPLOY_CONFIG="$CONFFILE" VAGRANT_VAGRANTFILE="$VAGRANTFILE" vagrant up "$NODE"
	popd
}

function do_stop_one () {
	NODE="$1"
        echo "Stop One Node \'$NODE\' with $CONFFILE"

        pushd ./vagrant
        env KUBE_VIRTDEPLOY_CONFIG="$CONFFILE" VAGRANT_VAGRANTFILE=Vagrantfile.worker vagrant destroy "$NODE"
        popd
}

function do_halt_one () {
	NODE="$1"

	echo "Shut down \`$NODE\`"

	pushd ./vagrant

	if [[ "$NODE" =~ "master" ]]; then
		VAGRANTFILE=Vagrantfile.server
	else
		VAGRANTFILE=Vagrantfile.worker
	fi

	if [ "x$FORCE" == x"0" ]; then
		env KUBE_VIRTDEPLOY_CONFIG="$CONFFILE" VAGRANT_VAGRANTFILE="$VAGRANTFILE" vagrant halt "$NODE"
	else
		env KUBE_VIRTDEPLOY_CONFIG="$CONFFILE" VAGRANT_VAGRANTFILE="$VAGRANTFILE" vagrant halt --force "$NODE"
	fi

	popd
}

##################################################
# Main logic.
##################################################
# parse arguments and options.
declare -a params=()

for OPT in "$@"
do
	case "$OPT" in
		'--config' )
			if [[ -z "${2:-}" ]] || [[ "${2:-}" =~ ^-+ ]]; then
				echo "${PROGNAME}: option '$1' requires an argument." 1>&2
				exit 1
			fi
			CONFFILE=`realpath "$2"`
			shift 2
		;;
		'--force' )
			FORCE=1
			shift 1
		;;
		-*)
			echo "${PROGNAME}: illegal option -- '$(echo $1 | sed 's/^-*//')'" 1>&2
			exit 1
			;;
		*)
			if [[ ! -z "${1:-}" ]] && [[ ! "${1:-}" =~ ^-+ ]]; then
				params+=( "$1" )
				shift 1
			fi
			;;
	esac
done

command="" && [ ${#params[@]} -ne 0 ] && command="${params[0]}"

case $command in
	'start' )
		if [ ${#params[@]} -eq 1 ]; then
			echo 'do_start'
			do_start
		elif [ ${#params[@]} -eq 2 ]; then
			do_start_one "${params[1]}"
		else
			exit 1
		fi
		;;
	'stop' )
		if [ ${#params[@]} -eq 1 ]; then
			do_stop
		elif [ ${#params[@]} -eq 2 ]; then
			do_stop_one "${params[1]}"
		else
			exit 1
		fi
		;;
	'start-basevm' )
		if [ ${#params[@]} -eq 1 ]; then
			do_start_basevm
		else
			exit 1
		fi
		;;
	'stop-basevm' )
		if [ ${#params[@]} -eq 1 ]; then
			do_stop_basevm
		else
			exit 1
		fi
		;;
	'halt' )
		if [ ${#params[@]} -eq 1 ]; then
			do_halt
		elif [ ${#params[@]} -eq 2 ]; then
			do_halt_one "${params[1]}"
		else
			exit 1
		fi
		;;
	'help' )
		usage
		exit 0
		;;
	'' )
		echo "Try \`${PROGNAME} help' for more information."
		exit 0
		;;
	*)
		echo "${PROGNAME}: illegal command '$command'" 1>&2
		exit 1
		;;
esac
